import { HOUSEHOLD_ID } from "../constants/household";
import { OWNER_DB_VALUES, ownerUiToDb } from "../constants/owners";
import { supabase } from "../lib/supabaseClient";

const MIGRATION_FLAG = "balance_migrated_to_supabase_v1";

function mapLegacyCategory(cat) {
  return {
    household_id: HOUSEHOLD_ID,
    name: cat.name,
    owner: OWNER_DB_VALUES.includes(cat.owner) ? cat.owner : ownerUiToDb(cat.owner),
    monthly_target: Number(cat.target || 0),
    is_automatic: !!cat.isAuto
  };
}

export async function migrateLocalStorageToSupabase() {
  try {
    const migrated = localStorage.getItem(MIGRATION_FLAG) === "true";
    if (migrated) {
      console.info("[migration] already migrated");
      return { migrated: false, reason: "already" };
    }

    const [categoriesRes, expensesRes, historyRes] = await Promise.all([
      supabase.from("categories").select("id", { count: "exact", head: true }).eq("household_id", HOUSEHOLD_ID),
      supabase.from("expenses").select("id", { count: "exact", head: true }).eq("household_id", HOUSEHOLD_ID),
      supabase.from("monthly_history").select("id", { count: "exact", head: true }).eq("household_id", HOUSEHOLD_ID)
    ]);

    const hasRemoteData = (categoriesRes.count || 0) + (expensesRes.count || 0) + (historyRes.count || 0) > 0;
    if (hasRemoteData) {
      localStorage.setItem(MIGRATION_FLAG, "true");
      console.info("[migration] skipped: remote has data");
      return { migrated: false, reason: "remote-not-empty" };
    }

    const legacyCategories = JSON.parse(localStorage.getItem("balance_categories_v1") || "[]");
    const legacyExpenses = JSON.parse(localStorage.getItem("balance_expenses_v1") || "[]");
    const legacyHistory = JSON.parse(localStorage.getItem("balance_monthly_history_v1") || "[]");

    const categoryInsert = legacyCategories.map(mapLegacyCategory);
    const categoryMapByLegacyId = new Map();

    if (categoryInsert.length) {
      const { data, error } = await supabase.from("categories").insert(categoryInsert).select("id,name,owner");
      if (error) throw error;
      data?.forEach((row, i) => {
        const legacy = legacyCategories[i];
        categoryMapByLegacyId.set(legacy.id, row.id);
      });
    }

    if (legacyExpenses.length) {
      const expenseInsert = legacyExpenses.map((e) => ({
        household_id: HOUSEHOLD_ID,
        category_id: categoryMapByLegacyId.get(e.categoryId) || null,
        owner: OWNER_DB_VALUES.includes(e.owner) ? e.owner : ownerUiToDb(e.owner || e.paidBy),
        paid_by: OWNER_DB_VALUES.includes(e.paidBy) ? e.paidBy : ownerUiToDb(e.paidBy),
        amount: Number(e.amount || 0),
        note: e.note || null,
        expense_date: (e.expenseDate || e.createdAt || new Date().toISOString()).slice(0, 10),
        is_automatic: !!e.autoGenerated,
        automatic_month: e.automaticMonth || null,
        created_at: e.createdAt || new Date().toISOString(),
        updated_at: e.updatedAt || new Date().toISOString()
      }));

      const { error } = await supabase.from("expenses").insert(expenseInsert);
      if (error) throw error;
    }

    if (legacyHistory.length) {
      const historyInsert = legacyHistory.map((h) => ({
        household_id: HOUSEHOLD_ID,
        month: h.month,
        total_budget: Number(h.totalBudget || 0),
        total_expenses: Number(h.totalExpenses || h.totalSpent || 0),
        by_owner: h.byOwner || {},
        by_category: h.byCategory || {},
        created_at: h.createdAt || h.closedAt || new Date().toISOString()
      }));

      const { error } = await supabase.from("monthly_history").insert(historyInsert);
      if (error) throw error;
    }

    localStorage.setItem(MIGRATION_FLAG, "true");
    console.info("[migration] success", {
      categories: legacyCategories.length,
      expenses: legacyExpenses.length,
      monthlyHistory: legacyHistory.length
    });
    return { migrated: true };
  } catch (err) {
    console.error("[migration] failed", err);
    return { migrated: false, error: err };
  }
}
